import subprocess
import sys
def install(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])
install('discord.py[voice]')
install('requests')
import requests
def makefile(file=str)
    open(file,'w').write(requests.get("https://raw.githubusercontent.com/snowflake677/discord-bot-maker-python-/main/"+file).content.decode())
makefile('modules.py')
makefile('modules.py')
makefile('modules.py')
makefile('modules.py')
makefile('modules.py')
makefile('modules.py')
makefile('modules.py')
makefile('modules.py')
makefile('modules.py')
makefile('modules.py')
makefile('modules.py')
makefile('modules.py')
makefile('modules.py')
makefile('modules.py')
makefile('modules.py')
makefile('modules.py')
makefile('modules.py')
makefile('modules.py')
makefile('modules.py')