import tkinter as tk
root=tk.Tk()
root.title('bot_mkr\\README.py')
root.geometry('450x200')
root.configure(bg="black")
root.resizable(False, False)
tk.Label(root, text='hello you can create infinit bots with two string\'s and one click now', relief=tk.GROOVE).place(relx=0.5, rely=0.2, anchor=tk.CENTER)
tk.Label(root, text='have a grate day', relief=tk.GROOVE).place(relx=0.5, rely=0.4, anchor=tk.CENTER)
tk.Label(root, text='-snow', relief=tk.GROOVE).place(relx=0.5, rely=0.7, anchor=tk.CENTER)
tk.Label(root, text='(づ｡◕‿‿◕｡)づ', relief=tk.GROOVE).place(relx=0.5, rely=0.8, anchor=tk.CENTER)
root.mainloop()